language: cpp
os: linux
compiler: gcc

before_script:
        - mkdir build
        - cd build
        - cmake ..
script:
        - make

after_success:
         - ./Test/gtest_run
         - bash <(curl -s https://codecov.io/bash)
