language: cpp
os:
  - linux
  - windows

before_script:
        - mkdir build
        - cd build
        - cmake -DBUILD_GUI=OFF ..
script:
        - cmake --build .
        - if [ "$TRAIVS_OS_NAME" = "windows" ]; then ./Test/Release/gtest_run.exe ; fi
        - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./Test/gtest_run ; fi
  
after_success:
         - bash <(curl -s https://codecov.io/bash)
