name: Coverage

on: [push]

env:
  BUILD_TYPE: debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true
      
    - name: Install packages
      run: sudo apt-get update ; sudo apt-get install xorg-dev libgl1-mesa-dev libglu1-mesa-dev lcov gcovr

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/Raytracer/build
      
    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/Raytracer/build
      run: cmake -DCMAKE_CXX_FLAGS="--coverage" $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      
    - name: Build
      working-directory: ${{runner.workspace}}/Raytracer/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/Raytracer
      shell: bash
      run: build/bin/gtest_run

    - name: Upload coverage to codecov.io
      working-directory: ${{runner.workspace}}/Raytracer
      run: bash <(curl -s https://codecov.io/bash)
